# Generated by Django 2.2.4 on 2019-08-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumCode', models.CharField(max_length=50, verbose_name='NumCode')),
                ('CharCode', models.CharField(max_length=50, verbose_name='CharCode')),
                ('Nominal', models.CharField(max_length=50, verbose_name='Nominal')),
                ('Name', models.CharField(max_length=50, verbose_name='Name')),
                ('Value', models.CharField(max_length=50, verbose_name='Value')),
            ],
        ),
    ]
